### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: "Generator Bristol"
email: office@usfolk.co.uk
description: 30,611 sq ft of outstanding, contemporary office space coming in 2019 to Bristol
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://generatorbuilding.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#FF4438'
# twitter_username: sandochee
# github_username:  sandoche
author: Usfolk
logo: assets/images/large-logo.png
# twitter:
#   username: sandochee
# social:
#   name: Sandoche Adittane
#   links:
#     - https://twitter.com/sandochee
#     - https://www.facebook.com/sandoche
#     - https://www.linkedin.com/in/sandoche
#     - https://plus.google.com/+SandocheADITTANE
#     - https://github.com/sandoche

languages: ["en"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: id
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - _fonts
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
